### ISSUE TITLE
Utils.getColors() 

### ISSUE THREAD

**Issue by selvamani-k-8445** [akshay2211/Ariana#1]
Eventhough im imported Butterknife library it shows the errror cannot find the getColors()  method

**Comment by akshay2211** [comment]
Hello @MaxxselvaK  ,
Thankyou for giving this library a try 
the **getColors()** method is in **_Utils Class_**


`public static int[] getColors() {
        return new int[]{
                Color.parseColor("#1BFFFF"),
                Color.parseColor("#2E3192"),
                Color.parseColor("#ED1E79"),
                Color.parseColor("#009E00"),
                Color.parseColor("#FBB03B"),
                Color.parseColor("#D4145A"),
                Color.parseColor("#3AA17E"),
                Color.parseColor("#00537E"),
        };
    }`
